version: "3.8"

services:
  # Backend: Symfony
  symfony-backend:
    image: php:8.2-fpm
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]

  # Frontend: Next.js
  nextjs-frontend:
    image: node:20
    container_name: nextjs-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - app-network
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/public:/var/www/html
      - ./frontend:/app
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge
